# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.video import Video  # noqa: E501
from twitter.rest import ApiException

class TestVideo(unittest.TestCase):
    """Video unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Video
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.video.Video()  # noqa: E501
        if include_optional :
            return Video(
                duration_ms = 56, 
                non_public_metrics = twitter.models.video_all_of_non_public_metrics.Video_allOf_non_public_metrics(
                    playback_0_count = 56, 
                    playback_100_count = 56, 
                    playback_25_count = 56, 
                    playback_50_count = 56, 
                    playback_75_count = 56, ), 
                organic_metrics = twitter.models.video_all_of_organic_metrics.Video_allOf_organic_metrics(
                    playback_0_count = 56, 
                    playback_100_count = 56, 
                    playback_25_count = 56, 
                    playback_50_count = 56, 
                    playback_75_count = 56, 
                    view_count = 56, ), 
                preview_image_url = '', 
                promoted_metrics = twitter.models.video_all_of_promoted_metrics.Video_allOf_promoted_metrics(
                    playback_0_count = 56, 
                    playback_100_count = 56, 
                    playback_25_count = 56, 
                    playback_50_count = 56, 
                    playback_75_count = 56, 
                    view_count = 56, ), 
                public_metrics = twitter.models.video_all_of_public_metrics.Video_allOf_public_metrics(
                    view_count = 56, ), 
                variants = [
                    twitter.models.variant.Variant(
                        bit_rate = 56, 
                        content_type = '', 
                        url = '', )
                    ]
            )
        else :
            return Video(
        )

    def testVideo(self):
        """Test Video"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
