# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import twitter
from twitter.api.users_api import UsersApi  # noqa: E501
from twitter.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = twitter.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_my_user(self):
        """Test case for find_my_user

        User lookup me  # noqa: E501
        """
        pass

    def test_find_user_by_id(self):
        """Test case for find_user_by_id

        User lookup by ID  # noqa: E501
        """
        pass

    def test_find_user_by_username(self):
        """Test case for find_user_by_username

        User lookup by username  # noqa: E501
        """
        pass

    def test_find_users_by_id(self):
        """Test case for find_users_by_id

        User lookup by IDs  # noqa: E501
        """
        pass

    def test_find_users_by_username(self):
        """Test case for find_users_by_username

        User lookup by usernames  # noqa: E501
        """
        pass

    def test_list_get_followers(self):
        """Test case for list_get_followers

        Returns User objects that follow a List by the provided List ID  # noqa: E501
        """
        pass

    def test_list_get_members(self):
        """Test case for list_get_members

        Returns User objects that are members of a List by the provided List ID.  # noqa: E501
        """
        pass

    def test_tweets_id_liking_users(self):
        """Test case for tweets_id_liking_users

        Returns User objects that have liked the provided Tweet ID  # noqa: E501
        """
        pass

    def test_tweets_id_retweeting_users(self):
        """Test case for tweets_id_retweeting_users

        Returns User objects that have retweeted the provided Tweet ID  # noqa: E501
        """
        pass

    def test_users_id_block(self):
        """Test case for users_id_block

        Block User by User ID  # noqa: E501
        """
        pass

    def test_users_id_blocking(self):
        """Test case for users_id_blocking

        Returns User objects that are blocked by provided User ID  # noqa: E501
        """
        pass

    def test_users_id_follow(self):
        """Test case for users_id_follow

        Follow User  # noqa: E501
        """
        pass

    def test_users_id_followers(self):
        """Test case for users_id_followers

        Followers by User ID  # noqa: E501
        """
        pass

    def test_users_id_following(self):
        """Test case for users_id_following

        Following by User ID  # noqa: E501
        """
        pass

    def test_users_id_mute(self):
        """Test case for users_id_mute

        Mute User by User ID.  # noqa: E501
        """
        pass

    def test_users_id_muting(self):
        """Test case for users_id_muting

        Returns User objects that are muted by the provided User ID  # noqa: E501
        """
        pass

    def test_users_id_unblock(self):
        """Test case for users_id_unblock

        Unblock User by User ID  # noqa: E501
        """
        pass

    def test_users_id_unfollow(self):
        """Test case for users_id_unfollow

        Unfollow User  # noqa: E501
        """
        pass

    def test_users_id_unmute(self):
        """Test case for users_id_unmute

        Unmute User by User ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
