# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.entity_indices_inclusive_inclusive import EntityIndicesInclusiveInclusive  # noqa: E501
from twitter.rest import ApiException

class TestEntityIndicesInclusiveInclusive(unittest.TestCase):
    """EntityIndicesInclusiveInclusive unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EntityIndicesInclusiveInclusive
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.entity_indices_inclusive_inclusive.EntityIndicesInclusiveInclusive()  # noqa: E501
        if include_optional :
            return EntityIndicesInclusiveInclusive(
                end = 61, 
                start = 50
            )
        else :
            return EntityIndicesInclusiveInclusive(
                end = 61,
                start = 50,
        )

    def testEntityIndicesInclusiveInclusive(self):
        """Test EntityIndicesInclusiveInclusive"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
