# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import twitter
from twitter.api.spaces_api import SpacesApi  # noqa: E501
from twitter.rest import ApiException


class TestSpacesApi(unittest.TestCase):
    """SpacesApi unit test stubs"""

    def setUp(self):
        self.api = twitter.api.spaces_api.SpacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_space_by_id(self):
        """Test case for find_space_by_id

        Space lookup by Space ID  # noqa: E501
        """
        pass

    def test_find_spaces_by_creator_ids(self):
        """Test case for find_spaces_by_creator_ids

        Space lookup by their creators  # noqa: E501
        """
        pass

    def test_find_spaces_by_ids(self):
        """Test case for find_spaces_by_ids

        Space lookup up Space IDs  # noqa: E501
        """
        pass

    def test_search_spaces(self):
        """Test case for search_spaces

        Search for Spaces  # noqa: E501
        """
        pass

    def test_space_buyers(self):
        """Test case for space_buyers

        Retrieve the list of Users who purchased a ticket to the given space  # noqa: E501
        """
        pass

    def test_space_tweets(self):
        """Test case for space_tweets

        Retrieve Tweets from a Space.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
