# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.tweet_compliance_stream_response_one_of1 import TweetComplianceStreamResponseOneOf1  # noqa: E501
from twitter.rest import ApiException

class TestTweetComplianceStreamResponseOneOf1(unittest.TestCase):
    """TweetComplianceStreamResponseOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TweetComplianceStreamResponseOneOf1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.tweet_compliance_stream_response_one_of1.TweetComplianceStreamResponseOneOf1()  # noqa: E501
        if include_optional :
            return TweetComplianceStreamResponseOneOf1(
                errors = [
                    twitter.models.problem.Problem(
                        detail = '', 
                        status = 56, 
                        title = '', 
                        type = '', )
                    ]
            )
        else :
            return TweetComplianceStreamResponseOneOf1(
                errors = [
                    twitter.models.problem.Problem(
                        detail = '', 
                        status = 56, 
                        title = '', 
                        type = '', )
                    ],
        )

    def testTweetComplianceStreamResponseOneOf1(self):
        """Test TweetComplianceStreamResponseOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
