# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.place_type import PlaceType  # noqa: E501
from twitter.rest import ApiException

class TestPlaceType(unittest.TestCase):
    """PlaceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlaceType(self):
        """Test PlaceType"""
        # inst = PlaceType()

if __name__ == '__main__':
    unittest.main()
