# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.compliance_job import ComplianceJob  # noqa: E501
from twitter.rest import ApiException

class TestComplianceJob(unittest.TestCase):
    """ComplianceJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ComplianceJob
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.compliance_job.ComplianceJob()  # noqa: E501
        if include_optional :
            return ComplianceJob(
                created_at = '2021-01-06T18:40:40Z', 
                download_expires_at = '2021-01-06T18:40:40Z', 
                download_url = '', 
                id = '1372966999991541762', 
                name = 'my-job', 
                status = 'created', 
                type = 'tweets', 
                upload_expires_at = '2021-01-06T18:40:40Z', 
                upload_url = ''
            )
        else :
            return ComplianceJob(
                created_at = '2021-01-06T18:40:40Z',
                download_expires_at = '2021-01-06T18:40:40Z',
                download_url = '',
                id = '1372966999991541762',
                status = 'created',
                type = 'tweets',
                upload_expires_at = '2021-01-06T18:40:40Z',
                upload_url = '',
        )

    def testComplianceJob(self):
        """Test ComplianceJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
