# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import twitter
from twitter.api.bookmarks_api import BookmarksApi  # noqa: E501
from twitter.rest import ApiException


class TestBookmarksApi(unittest.TestCase):
    """BookmarksApi unit test stubs"""

    def setUp(self):
        self.api = twitter.api.bookmarks_api.BookmarksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_users_id_bookmarks(self):
        """Test case for get_users_id_bookmarks

        Bookmarks by User  # noqa: E501
        """
        pass

    def test_post_users_id_bookmarks(self):
        """Test case for post_users_id_bookmarks

        Add Tweet to Bookmarks  # noqa: E501
        """
        pass

    def test_users_id_bookmarks_delete(self):
        """Test case for users_id_bookmarks_delete

        Remove a bookmarked Tweet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
