# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import twitter
from twitter.api.compliance_api import ComplianceApi  # noqa: E501
from twitter.rest import ApiException


class TestComplianceApi(unittest.TestCase):
    """ComplianceApi unit test stubs"""

    def setUp(self):
        self.api = twitter.api.compliance_api.ComplianceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_batch_compliance_job(self):
        """Test case for create_batch_compliance_job

        Create compliance job  # noqa: E501
        """
        pass

    def test_get_batch_compliance_job(self):
        """Test case for get_batch_compliance_job

        Get Compliance Job  # noqa: E501
        """
        pass

    def test_get_tweets_compliance_stream(self):
        """Test case for get_tweets_compliance_stream

        Tweets Compliance stream  # noqa: E501
        """
        pass

    def test_get_users_compliance_stream(self):
        """Test case for get_users_compliance_stream

        Users Compliance stream  # noqa: E501
        """
        pass

    def test_list_batch_compliance_jobs(self):
        """Test case for list_batch_compliance_jobs

        List Compliance Jobs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
