# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.tweet_create_request import TweetCreateRequest  # noqa: E501
from twitter.rest import ApiException

class TestTweetCreateRequest(unittest.TestCase):
    """TweetCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TweetCreateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.tweet_create_request.TweetCreateRequest()  # noqa: E501
        if include_optional :
            return TweetCreateRequest(
                direct_message_deep_link = '', 
                for_super_followers_only = True, 
                geo = twitter.models.tweet_create_request_geo.TweetCreateRequest_geo(
                    place_id = '', ), 
                media = twitter.models.tweet_create_request_media.TweetCreateRequest_media(
                    media_ids = [
                        '1146654567674912769'
                        ], 
                    tagged_user_ids = [
                        '2244994945'
                        ], ), 
                poll = twitter.models.tweet_create_request_poll.TweetCreateRequest_poll(
                    duration_minutes = 5, 
                    options = [
                        '0'
                        ], 
                    reply_settings = 'following', ), 
                quote_tweet_id = '1346889436626259968', 
                reply = twitter.models.tweet_create_request_reply.TweetCreateRequest_reply(
                    exclude_reply_user_ids = [
                        '2244994945'
                        ], 
                    in_reply_to_tweet_id = '1346889436626259968', ), 
                reply_settings = 'following', 
                text = 'Learn how to use the user Tweet timeline and user mention timeline endpoints in the Twitter API v2 to explore Tweet\u2026 https:\/\/t.co\/56a0vZUx7i'
            )
        else :
            return TweetCreateRequest(
        )

    def testTweetCreateRequest(self):
        """Test TweetCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
