# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.rules_request_summary_one_of1 import RulesRequestSummaryOneOf1  # noqa: E501
from twitter.rest import ApiException

class TestRulesRequestSummaryOneOf1(unittest.TestCase):
    """RulesRequestSummaryOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RulesRequestSummaryOneOf1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.rules_request_summary_one_of1.RulesRequestSummaryOneOf1()  # noqa: E501
        if include_optional :
            return RulesRequestSummaryOneOf1(
                deleted = 56, 
                not_deleted = 56
            )
        else :
            return RulesRequestSummaryOneOf1(
                deleted = 56,
                not_deleted = 56,
        )

    def testRulesRequestSummaryOneOf1(self):
        """Test RulesRequestSummaryOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
