# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.get2_tweets_id_quote_tweets_response_meta import Get2TweetsIdQuoteTweetsResponseMeta  # noqa: E501
from twitter.rest import ApiException

class TestGet2TweetsIdQuoteTweetsResponseMeta(unittest.TestCase):
    """Get2TweetsIdQuoteTweetsResponseMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Get2TweetsIdQuoteTweetsResponseMeta
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.get2_tweets_id_quote_tweets_response_meta.Get2TweetsIdQuoteTweetsResponseMeta()  # noqa: E501
        if include_optional :
            return Get2TweetsIdQuoteTweetsResponseMeta(
                next_token = '0', 
                result_count = 56
            )
        else :
            return Get2TweetsIdQuoteTweetsResponseMeta(
        )

    def testGet2TweetsIdQuoteTweetsResponseMeta(self):
        """Test Get2TweetsIdQuoteTweetsResponseMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
