# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.tweet_create_request_media import TweetCreateRequestMedia  # noqa: E501
from twitter.rest import ApiException

class TestTweetCreateRequestMedia(unittest.TestCase):
    """TweetCreateRequestMedia unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TweetCreateRequestMedia
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.tweet_create_request_media.TweetCreateRequestMedia()  # noqa: E501
        if include_optional :
            return TweetCreateRequestMedia(
                media_ids = [
                    '1146654567674912769'
                    ], 
                tagged_user_ids = [
                    '2244994945'
                    ]
            )
        else :
            return TweetCreateRequestMedia(
                media_ids = [
                    '1146654567674912769'
                    ],
        )

    def testTweetCreateRequestMedia(self):
        """Test TweetCreateRequestMedia"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
