# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.compliance_job_status import ComplianceJobStatus  # noqa: E501
from twitter.rest import ApiException

class TestComplianceJobStatus(unittest.TestCase):
    """ComplianceJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComplianceJobStatus(self):
        """Test ComplianceJobStatus"""
        # inst = ComplianceJobStatus()

if __name__ == '__main__':
    unittest.main()
