# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.tweet_drop_compliance_schema import TweetDropComplianceSchema  # noqa: E501
from twitter.rest import ApiException

class TestTweetDropComplianceSchema(unittest.TestCase):
    """TweetDropComplianceSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TweetDropComplianceSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.tweet_drop_compliance_schema.TweetDropComplianceSchema()  # noqa: E501
        if include_optional :
            return TweetDropComplianceSchema(
                drop = twitter.models.tweet_compliance_schema.TweetComplianceSchema(
                    event_at = '2021-07-06T18:40:40Z', 
                    quote_tweet_id = '1346889436626259968', 
                    tweet = twitter.models.tweet_compliance_schema_tweet.TweetComplianceSchema_tweet(
                        author_id = '2244994945', 
                        id = '1346889436626259968', ), )
            )
        else :
            return TweetDropComplianceSchema(
                drop = twitter.models.tweet_compliance_schema.TweetComplianceSchema(
                    event_at = '2021-07-06T18:40:40Z', 
                    quote_tweet_id = '1346889436626259968', 
                    tweet = twitter.models.tweet_compliance_schema_tweet.TweetComplianceSchema_tweet(
                        author_id = '2244994945', 
                        id = '1346889436626259968', ), ),
        )

    def testTweetDropComplianceSchema(self):
        """Test TweetDropComplianceSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
