# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import twitter
from twitter.api.general_api import GeneralApi  # noqa: E501
from twitter.rest import ApiException


class TestGeneralApi(unittest.TestCase):
    """GeneralApi unit test stubs"""

    def setUp(self):
        self.api = twitter.api.general_api.GeneralApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_open_api_spec(self):
        """Test case for get_open_api_spec

        Returns the OpenAPI Specification document.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
