# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.reply_settings import ReplySettings  # noqa: E501
from twitter.rest import ApiException

class TestReplySettings(unittest.TestCase):
    """ReplySettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReplySettings(self):
        """Test ReplySettings"""
        # inst = ReplySettings()

if __name__ == '__main__':
    unittest.main()
