# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.list_create_response import ListCreateResponse  # noqa: E501
from twitter.rest import ApiException

class TestListCreateResponse(unittest.TestCase):
    """ListCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListCreateResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.list_create_response.ListCreateResponse()  # noqa: E501
        if include_optional :
            return ListCreateResponse(
                data = twitter.models.list_create_response_data.ListCreateResponse_data(
                    id = '1146654567674912769', 
                    name = '', ), 
                errors = [
                    twitter.models.problem.Problem(
                        detail = '', 
                        status = 56, 
                        title = '', 
                        type = '', )
                    ]
            )
        else :
            return ListCreateResponse(
        )

    def testListCreateResponse(self):
        """Test ListCreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
