# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.url_fields import UrlFields  # noqa: E501
from twitter.rest import ApiException

class TestUrlFields(unittest.TestCase):
    """UrlFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UrlFields
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.url_fields.UrlFields()  # noqa: E501
        if include_optional :
            return UrlFields(
                description = 'This is a description of the website.', 
                display_url = 'twittercommunity.com/t/introducing-…', 
                expanded_url = 'https://developer.twitter.com/en/docs/twitter-api', 
                images = [
                    twitter.models.url_image.UrlImage(
                        height = 0, 
                        url = 'https://developer.twitter.com/en/docs/twitter-api', 
                        width = 0, )
                    ], 
                media_key = '4_072888001528021798096225500850762068629', 
                status = 100, 
                title = 'Introducing the v2 follow lookup endpoints', 
                unwound_url = 'https://twittercommunity.com/t/introducing-the-v2-follow-lookup-endpoints/147118', 
                url = 'https://developer.twitter.com/en/docs/twitter-api'
            )
        else :
            return UrlFields(
                url = 'https://developer.twitter.com/en/docs/twitter-api',
        )

    def testUrlFields(self):
        """Test UrlFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
