# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import twitter
from twitter.models.tweet_attachments import TweetAttachments  # noqa: E501
from twitter.rest import ApiException

class TestTweetAttachments(unittest.TestCase):
    """TweetAttachments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TweetAttachments
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = twitter.models.tweet_attachments.TweetAttachments()  # noqa: E501
        if include_optional :
            return TweetAttachments(
                media_keys = [
                    '4_072888001528021798096225500850762068629'
                    ], 
                poll_ids = [
                    '1365059861688410112'
                    ]
            )
        else :
            return TweetAttachments(
        )

    def testTweetAttachments(self):
        """Test TweetAttachments"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
