# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, constr

from pydantic import ValidationError

class Get2ListsIdFollowersResponseMeta(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    next_token: Optional[constr(strict=True, min_length=1)] = Field(None, description="The next token.")
    previous_token: Optional[constr(strict=True, min_length=1)] = Field(None, description="The previous token.")
    result_count: Optional[StrictInt] = Field(None, description="The number of results returned in this response.")

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Get2ListsIdFollowersResponseMeta:
        """Create an instance of Get2ListsIdFollowersResponseMeta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude_none=True)

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Get2ListsIdFollowersResponseMeta:
        """Create an instance of Get2ListsIdFollowersResponseMeta from a dict"""
        if type(obj) is not dict:
            return Get2ListsIdFollowersResponseMeta.parse_obj(obj)

        return Get2ListsIdFollowersResponseMeta.parse_obj({
            "next_token": obj.get("next_token"),
            "previous_token": obj.get("previous_token"),
            "result_count": obj.get("result_count")
        })


