# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, conint, constr

from pydantic import ValidationError

class MentionEntity(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    end: conint(strict=True, ge=0) = Field(..., description="Index (zero-based) at which position this entity ends.  The index is exclusive.")
    start: conint(strict=True, ge=0) = Field(..., description="Index (zero-based) at which position this entity starts.  The index is inclusive.")
    id: Optional[constr(strict=True, regex=r'/^[0-9]{1,19}$/')] = Field(None, description="Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.")
    username: constr(strict=True, regex=r'/^[A-Za-z0-9_]{1,15}$/') = Field(..., description="The Twitter handle (screen name) of this user.")

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MentionEntity:
        """Create an instance of MentionEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude_none=True)

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MentionEntity:
        """Create an instance of MentionEntity from a dict"""
        if type(obj) is not dict:
            return MentionEntity.parse_obj(obj)

        return MentionEntity.parse_obj({
            "end": obj.get("end"),
            "start": obj.get("start"),
            "id": obj.get("id"),
            "username": obj.get("username")
        })


