# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt

from pydantic import ValidationError

class TweetPublicMetrics(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    like_count: StrictInt = Field(..., description="Number of times this Tweet has been liked.")
    quote_count: Optional[StrictInt] = Field(None, description="Number of times this Tweet has been quoted.")
    reply_count: StrictInt = Field(..., description="Number of times this Tweet has been replied to.")
    retweet_count: StrictInt = Field(..., description="Number of times this Tweet has been Retweeted.")

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TweetPublicMetrics:
        """Create an instance of TweetPublicMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude_none=True)

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TweetPublicMetrics:
        """Create an instance of TweetPublicMetrics from a dict"""
        if type(obj) is not dict:
            return TweetPublicMetrics.parse_obj(obj)

        return TweetPublicMetrics.parse_obj({
            "like_count": obj.get("like_count"),
            "quote_count": obj.get("quote_count"),
            "reply_count": obj.get("reply_count"),
            "retweet_count": obj.get("retweet_count")
        })


