# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt

from pydantic import ValidationError

class UserPublicMetrics(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    followers_count: StrictInt = Field(..., description="Number of Users who are following this User.")
    following_count: StrictInt = Field(..., description="Number of Users this User is following.")
    listed_count: StrictInt = Field(..., description="The number of lists that include this User.")
    tweet_count: StrictInt = Field(..., description="The number of Tweets (including Retweets) posted by this User.")

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UserPublicMetrics:
        """Create an instance of UserPublicMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude_none=True)

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UserPublicMetrics:
        """Create an instance of UserPublicMetrics from a dict"""
        if type(obj) is not dict:
            return UserPublicMetrics.parse_obj(obj)

        return UserPublicMetrics.parse_obj({
            "followers_count": obj.get("followers_count"),
            "following_count": obj.get("following_count"),
            "listed_count": obj.get("listed_count"),
            "tweet_count": obj.get("tweet_count")
        })


