# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints  # noqa: E501

    The version of the OpenAPI document: 2.49
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

from pydantic import ValidationError

class Variant(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    bit_rate: Optional[StrictInt] = Field(None, description="The bit rate of the media.")
    content_type: Optional[StrictStr] = Field(None, description="The content type of the media.")
    url: Optional[StrictStr] = Field(None, description="The url to the media.")

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Variant:
        """Create an instance of Variant from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude_none=True)

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Variant:
        """Create an instance of Variant from a dict"""
        if type(obj) is not dict:
            return Variant.parse_obj(obj)

        return Variant.parse_obj({
            "bit_rate": obj.get("bit_rate"),
            "content_type": obj.get("content_type"),
            "url": obj.get("url")
        })


